import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NutriScan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <Link
          href="/chat"
          className="
            fixed
            bottom-4 right-4
            md:bottom-6 md:right-6
            z-50
            rounded-full
            bg-[#004743]
            px-4 py-3
            md:px-5 md:py-4
            text-sm md:text-base
            font-semibold
            text-white
            shadow-lg
            hover:bg-[#003731]
            transition-colors
          "
        >
          Chat with NutriScan
        </Link>

        <main className="min-h-screen w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
