import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Health Boot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <Link
          href="/chat"
          className="
            fixed
            bottom-4 right-4
            md:bottom-6 md:right-6
            z-50
            rounded-full
            bg-slate-900
            px-4 py-3
            md:px-5 md:py-4
            text-sm md:text-base
            font-semibold
            text-white
            shadow-lg
            hover:bg-cyan-600
            transition-colors"
        >
          Chat with Health Boot
        </Link>

        <main className="w-full min-h-screen">
          {children}
        </main>
        
        {/* Global Footer */}
        <footer className="w-full text-center py-4 text-sm text-slate-500 mt-auto bg-[#F4F7FB]">
          Coded by Kavinila and Arunaw Rishe M...
        </footer>
      </body>
    </html>
  );
}
