import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NutriScan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${inter.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Link
          href="/chat"
          className="fixed bottom-5 right-5 z-50 rounded-full bg-[#004743] px-4 py-3 text-sm font-semibold text-white shadow-lg transition-colors hover:bg-[#003731]"
        >
          Chat with NutriScan
        </Link>
        <main className="min-h-screen max-w-[450px] mx-auto">{children}</main>
      </body>
    </html>
  );
}
