package models

import (
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type BiometricInput struct {
	Gender      string `json:"gender" binding:"required"` // Added for BMR & Body Fat rules
	Weight      string `json:"weight" binding:"required"`
	HeartRate   string `json:"heartRate" binding:"required"`
	SystolicBP  string `json:"systolicBP" binding:"required"`
	DiastolicBP string `json:"diastolicBP" binding:"required"`
	Water       string `json:"water" binding:"required"`
	BodyFat     string `json:"bodyFat" binding:"required"`
	Muscle      string `json:"muscle" binding:"required"`
	VisceralFat string `json:"visceralFat" binding:"required"`
	BoneMass    string `json:"boneMass" binding:"required"`
}

type BiometricAnalysisResponse struct {
	RawInput BiometricInput `json:"rawInput"`
	
	// Deterministic Analytics (Calculated in Go)
	BMI                         string `json:"bmi"`
	BMIClassification           string `json:"bmiClassification"`
	BMIReason                   string `json:"bmiReason"`
	BodyFatClassification       string `json:"bodyFatClassification"`
	BodyFatReason               string `json:"bodyFatReason"`
	HeartRateClassification     string `json:"heartRateClassification"`
	HeartRateReason             string `json:"heartRateReason"`
	BloodPressureClassification string `json:"bloodPressureClassification"`
	BloodPressureReason         string `json:"bloodPressureReason"`
	HydrationStatus             string `json:"hydrationStatus"`
	HydrationReason             string `json:"hydrationReason"`
	BMR                         string `json:"bmr"`
	BMRReason                   string `json:"bmrReason"`
	DailyCalorieRequirement     string `json:"dailyCalorieRequirement"`
	DailyCalorieReason          string `json:"dailyCalorieReason"`
	IdealWeightRange            string `json:"idealWeightRange"`
	IdealWeightReason           string `json:"idealWeightReason"`
	RiskScore                   string `json:"riskScore"`
	RiskScoreReason             string `json:"riskScoreReason"`

	// Personalized Recommendations (Generated by Gemini AI)
	NutritionAdvice string `json:"nutritionAdvice"`
	HydrationAlerts string `json:"hydrationAlerts"`
	WellnessGoals   string `json:"wellnessGoals"`
	LifestyleTips   string `json:"lifestyleTips"`
	MealPlanForDay  string `json:"mealPlanForDay"`
	WorkoutPlan     string `json:"workoutPlan"`
}

type BiometricScanRecord struct {
	ID        primitive.ObjectID        `json:"id" bson:"_id,omitempty"`
	UserID    primitive.ObjectID        `json:"userId" bson:"userId"`
	CreatedAt primitive.DateTime        `json:"createdAt" bson:"createdAt"`
	Analysis  BiometricAnalysisResponse `json:"analysis" bson:"analysis"`
}
